#!/bin/bash
#PBS -l select=1:ncpus=40:mpiprocs=40:mem=30GB
#PBS -l walltime=06:00:00
#PBS -q short_cpuQ
#PBS -N GM_hdpr_mtx
#PBS -o GM_hdpr_mtx_o
#PBS -e GM_hdpr_mtx_e

# This is a comment.
# From the /home in the compute node we move to the
# directory from which we launched the job
# (and where you, hopefully, have your files)

# Specify to use only one openmp thread per MPI proc
export OMP_NUM_THREADS=1

module load gromacs-2021.4

cd $PBS_O_WORKDIR

gmx grompp -f step4.0_minimization.mdp -c step3_input.gro  -p topol.top -n index.ndx -t step3_input.cpt -o step4.0_minimization.tpr
wait
mpirun -np 40 gmx_mpi mdrun -v -deffnm step4.0_minimization -maxh 5.9