#!/bin/bash
#PBS -l select=1:ncpus=16:mpiprocs=16:mem=15GB
#PBS -l walltime=06:00:00
#PBS -q VARIAMOLS_cpuQ
#PBS -N md_run_WT


module load openmpi-3.0.0
module load gromacs-2021.4

cd $PBS_O_WORKDIR
export OMP_NUM_THREADS=1
#export GMX=/apps/gromacs-2018/bin/

# modify maxh so that it is slightly shorter than walltime. maxh is in hours
mpirun -np 16 gmx_mpi mdrun -s ./run.tpr -maxh 5.95 -deffnm run
