#!/bin/bash
#PBS -l select=1:ncpus=16:mpiprocs=16:mem=20GB
#PBS -l walltime=00:30:00
#PBS -q short_cpuQ
#PBS -N GM_hdpr
#PBS -o GM_hdpr_o
#PBS -e GM_hdpr_e

# This is a comment.
# From the /home in the compute node we move to the
# directory from which we launched the job
# (and where you, hopefully, have your files)

# Specify to use only one openmp thread per MPI proc
export OMP_NUM_THREADS=1

module load gromacs-2021.4

cd $PBS_O_WORKDIR

gmx grompp -f step4.1_equilibration.mdp -c step4.0_minimization.gro -r step4.0_minimization.gro -p topol.top -n index.ndx  -o step4.1_equilibration.tpr
wait
mpirun -np 16 gmx_mpi mdrun -v -deffnm step4.1_equilibration -maxh 0.2