#!/bin/bash
#PBS -l select=1:ncpus={{number_cpu}}:mpiprocs={{number_mpiprocs}}:mem={{memory_GB}}GB
#PBS -l walltime={{pbs_walltime}}
#PBS -q {{queue}}
#PBS -N {{job_name}}
#PBS -o {{job_out_name}}
#PBS -e {{job_err_name}}

# This is a comment.
# From the /home in the compute node we move to the
# directory from which we launched the job
# (and where you, hopefully, have your files)

# Specify to use only one openmp thread per MPI proc
export OMP_NUM_THREADS={{number_threads}}

module load gromacs-2021.4

cd $PBS_O_WORKDIR

mpirun -np {{number_mpiprocs}} gmx_mpi mdrun -v -s {{deffnm}}.tpr -cpi {{deffnm}}_prev.cpt -append -deffnm {{deffnm}} -maxh {{gmx_walltime}}
