#!/bin/bash
#PBS -l select=1:ncpus=30:mpiprocs=30:mem=20GB
#PBS -l walltime=04:00:00
#PBS -q short_cpuQ
#PBS -N GM_hdpr
#PBS -o GM_hdpr_o
#PBS -e GM_hdpr_e

# This is a comment.
# From the /home in the compute node we move to the
# directory from which we launched the job
# (and where you, hopefully, have your files)

# Specify to use only one openmp thread per MPI proc
export OMP_NUM_THREADS=1

module load gromacs-2021.4

cd $PBS_O_WORKDIR

gmx grompp -f step5_production.mdp -c step5_npt_restricted.gro  -p topol.top -n index.ndx -t step5_npt_restricted.cpt -o step5_production.tpr
wait
mpirun -np 30 gmx_mpi mdrun -v -deffnm step5_production -maxh 3.8
