#!/bin/bash
#PBS -l select=1:ncpus=25:mpiprocs=25:mem=20GB
#PBS -l walltime=06:00:00
#PBS -q short_cpuQ
#PBS -N dhfr_mtx_umbrella


module load openmpi-3.0.0
module load gromacs-2021.4

cd $PBS_O_WORKDIR
export OMP_NUM_THREADS=1

# modify maxh so that it is slightly shorter than walltime. maxh is in hours
mpirun -np 20 gmx_mpi mdrun -s ./{{deffnm}}.tpr -cpi {{input_conf}}.cpt -px {{deffnm}}_pullx.xvg -pf {{deffnm}}_pullf.xvg -maxh 5.95 -deffnm {{deffnm}}
