#!/bin/bash
#PBS -l select=1:ncpus=25:mpiprocs=25:mem=20GB
#PBS -l walltime=06:00:00
#PBS -q short_cpuQ
#PBS -N dhfr_mtx_umbrella


module load openmpi-3.0.0
module load gromacs-2021.4

cd $PBS_O_WORKDIR
export OMP_NUM_THREADS=1

# modify maxh so that it is slightly shorter than walltime. maxh is in hours
gmx grompp -f md_umbrella.mdp -c equil.gro -r equil.gro -p topol.top -n index.ndx -t equil.cpt -maxwarn 1 -o mdrun.tpr
mpirun -np 20 gmx_mpi mdrun -s ./mdrun.tpr -maxh 5.95 -deffnm mdrun